version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.dbdata/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ale123456
      MYSQL_DATABASE: base
      MYSQL_USER: root
      MYSQL_PASSWORD: Ale123456

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "80:80" 
      - "443:443"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Ale123456

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80" 
    restart: always


